### ISSUE TITLE
Allow setting weak deps per dep

### ISSUE THREAD

**Issue by Itxaka** [spectrocloud-labs/herd#1]
Currently you can mark only all of your deps as weak. So if you have some needed deps but one or two optional deps you cannot set them differently.

A nice solution would be to on dep adding, you could mark it as weak

```
herd.Add(
	"job4",
	herd.WithDeps("job1", "job2"),
	herd.WithWeakDeps("job3"),
	herd.WithCallback(func(ctx context.Context) error { return nil }),
)
```

**Comment by mudler** [comment]
Fixed in https://github.com/spectrocloud-labs/herd/releases/tag/v0.4.1 !
