### ISSUE TITLE
Have a way to identify if a GraphEntry was executed or not

### ISSUE THREAD

**Issue by Itxaka** [spectrocloud-labs/herd#2]
If I run and then display the dag with `Graph.Analyze` I can see if it failed or not, but I have no idea if it was executed or not.

Would really love to be able to check if it was run or not directly by doing something like

```
for i, layer := range g.Analyze() {
		for _, op := range layer {
			fmt.Printf("%s -> %t\n",op.Name, op.Finished/Executed)
		}	
}
```

**Comment by mudler** [comment]
good point!
